In [33]:
# Question 1
# Create a numpy array with 10 elements of the shape(10,1) using np.random and 
# find out the mean of the elements using basic numpy functions.

import numpy as np

x = np.random.random((10,1))
print(x)

[[0.22484497]
 [0.01595323]
 [0.99731052]
 [0.59529523]
 [0.4264895 ]
 [0.75267753]
 [0.34446185]
 [0.00325063]
 [0.87666634]
 [0.698536  ]]


In [34]:
x.shape

(10, 1)

In [35]:
np.mean(x)

0.4935485803152241

In [110]:
# Question 2
# Create a numpy array with 20 elements of the shape(20,1) using np.random 
# find the variance and standard deviation of the elements.

y = np.random.random((20,1))
y

array([[0.30021429],
       [0.54647886],
       [0.54902951],
       [0.25690755],
       [0.65687129],
       [0.54088133],
       [0.2342293 ],
       [0.52155547],
       [0.52091101],
       [0.45682999],
       [0.33395967],
       [0.78582443],
       [0.35609766],
       [0.82952068],
       [0.2248675 ],
       [0.57836975],
       [0.95602298],
       [0.48306176],
       [0.74548281],
       [0.81532665]])

In [111]:
y.shape

(20, 1)

In [38]:
print("Standard Deviation of array is",np.std(y))

print("Varidance of array is",np.var(y))

Standard Deviation of array is 0.26128025145931966


In [113]:
# Question 3
# Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. 
# Print the matrix which is the matrix multiplication of A and B. 
# The shape of the new matrix should be (10,25). 
# Using basic numpy math functions only find the sum of all the elements of the new matrix.

A = np.random.random((10,20))
A

array([[0.5231023 , 0.96921076, 0.5252504 , 0.5881509 , 0.64572492,
        0.92442248, 0.33243399, 0.16232655, 0.11549535, 0.66631069,
        0.95269417, 0.05206238, 0.19349416, 0.39179011, 0.18226438,
        0.95065856, 0.00880253, 0.51243861, 0.02630302, 0.91738295],
       [0.24024549, 0.93603916, 0.67201911, 0.231945  , 0.29648759,
        0.01641516, 0.21151432, 0.74729649, 0.14575993, 0.22475888,
        0.89162413, 0.95945531, 0.94066119, 0.84696145, 0.46587092,
        0.04003799, 0.61396322, 0.14834639, 0.32350402, 0.25175876],
       [0.25226144, 0.05022867, 0.30361408, 0.07026843, 0.28001132,
        0.30245444, 0.70241308, 0.22686368, 0.16888624, 0.57336874,
        0.62469401, 0.02078305, 0.60048551, 0.16205599, 0.75533247,
        0.29377985, 0.84046081, 0.7592075 , 0.23021754, 0.1358136 ],
       [0.67124428, 0.86969134, 0.55172311, 0.97426729, 0.79686189,
        0.22769158, 0.03010217, 0.16936268, 0.159255  , 0.88715574,
        0.59610872, 0.44901731, 0.77862466, 0

In [114]:
B = np.random.random((20,25))
B

array([[0.37158725, 0.49488394, 0.23739193, 0.49272137, 0.22579141,
        0.93293834, 0.5368246 , 0.60252284, 0.86084027, 0.14687785,
        0.64763204, 0.4612241 , 0.09185811, 0.34555555, 0.70724994,
        0.22208635, 0.19942924, 0.8019728 , 0.77358693, 0.11066289,
        0.45216479, 0.20632393, 0.0758379 , 0.5914958 , 0.85322852],
       [0.67495676, 0.19345938, 0.39089489, 0.31831933, 0.55066179,
        0.86872208, 0.16052859, 0.67099165, 0.4463567 , 0.74003797,
        0.31723575, 0.93965636, 0.70108655, 0.20587941, 0.7915236 ,
        0.42343186, 0.45612679, 0.33597343, 0.82764217, 0.88796249,
        0.68772877, 0.94921973, 0.8210388 , 0.48351866, 0.13296614],
       [0.77231261, 0.96039135, 0.22915315, 0.20259432, 0.12154947,
        0.45162122, 0.22055048, 0.82034498, 0.99394657, 0.47135752,
        0.73882927, 0.92811388, 0.98956651, 0.09803839, 0.01602143,
        0.92517109, 0.58193287, 0.7658405 , 0.84695353, 0.96447924,
        0.70452814, 0.38559493, 0.73857526, 0.

In [115]:
New = np.matmul(A,B)
New

array([[5.54169084, 4.88202209, 5.36139992, 4.84007539, 5.06242944,
        4.60589133, 4.07567371, 5.92714316, 5.94473594, 4.87850531,
        4.99316264, 4.97872374, 6.13996801, 3.99814331, 4.66503469,
        4.99910963, 4.46681635, 5.27570558, 5.11953106, 3.97763955,
        4.54213984, 3.71392381, 4.82390031, 3.94188038, 5.44733297],
       [5.53529733, 4.77714882, 5.04120289, 5.23830904, 3.67377811,
        5.16299369, 3.43966493, 5.83909622, 4.18113203, 4.01043857,
        4.57635381, 4.77887244, 5.40029615, 4.38094366, 4.1443341 ,
        4.95327616, 3.94070405, 4.85550411, 5.52002637, 4.82154116,
        3.97710335, 3.67466145, 4.50535078, 4.19316483, 4.90048228],
       [4.44386953, 4.15751725, 4.32365109, 4.28762604, 2.99868657,
        3.22134373, 2.98961646, 3.9031431 , 3.3841181 , 3.01984611,
        3.74113255, 3.38817391, 4.22343942, 3.50271223, 3.18983035,
        4.30951561, 3.91043078, 4.14167459, 3.84570072, 2.4553382 ,
        3.31144928, 2.68174757, 3.67677924, 2.

In [119]:
New.shape


(10, 25)

In [120]:
New.sum()

1298.5542155089229

In [106]:
# Question 4
# Create a numpy array A of shape(10,1).
# Using the basic operations of the numpy array generate an array of shape(10,1) 
# such that each element is the following function applied on each element of A. 

# f(x)=1 / (1 + exp(-x)) 
# Apply this function to each element of A and print the new array holding the value the function returns
# Example:

# a=[a1,a2,a3]n(new array to be printed )=[ f(a1), f(a2), f(a3)]

In [107]:
a = np.random.rand(10,1)

In [108]:
a = list((map( lambda x:1 / (1 + np.exp(-x) ), a ) ) )

In [109]:
a = np.array(a)
a

array([[0.68825143],
       [0.69957135],
       [0.56850511],
       [0.68518684],
       [0.52359193],
       [0.52677411],
       [0.57849509],
       [0.53915843],
       [0.7112526 ],
       [0.55184835]])